---
title: "cov_pcr_meta"
author: "Filbert Hong"
date: "5/14/2021"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
```
read file
```{r read}
sourcefile <- list.files() %>% subset(grepl("cov_pcr_sera",.) & grepl("RDS",.)) %>% subset(!grepl("nomask|yesmask|allsets|paired",.))
if (length(sourcefile)>1) {
  print("multiple versions present")
  stop()
}
cov_pcr_sera <- readRDS(file=sourcefile)
```
meta analyzer
```{r meta1}
cov_classes <- cov_pcr_sera %>% lapply(function(x) {x %>% lapply(class)})
cov_meta <- list()
for (q in 1:length(cov_pcr_sera)) {
  i <- cov_pcr_sera[[q]]
  iframe <- data.frame()
  for (r in 1:ncol(i)) {
    j <- i[,r] %>% unlist()
    namej <- colnames(i)[r]
    typej1 <- i[,r] %>% class() %>% head(1)
    typej <- typej1
    if (typej1=="tbl_df") {
      typej <- i[,r][[1]] %>% class()
      if (typej=="Date") {
        j <- j %>% as.Date(origin="1970-01-01")
      }
    }
    jcouldbenum <- F
    if ((typej=="character") & (length(unique(j))==length((as.numeric(j) %>% unique())))) {
      jcouldbenum <- T
      j <- as.numeric(j)
    }
    if ((typej %in% c("Date","integer","numeric","POSIXct","POSIXt")) | jcouldbenum) {
      minj <- min(j %>% na.omit()) %>% as.character()
      maxj <- max(j %>% na.omit()) %>% as.character()
      jvals <- NA
    } else {
      minj <- NA
      maxj <- NA
      if ((length(unique(j))>50) & !jcouldbenum) {
        jvals <- "numerous identifiers"
      } else {
        jvals <- j %>% as.character() %>% unique() %>% sort(na.last=T) %>% paste(collapse=";")
      }
    }
    hasNAs <- (NA %in% j)
    k <- c(namej,typej,jcouldbenum,hasNAs,minj,maxj,jvals)
    names(k) <- c("varname","varclass","couldbenum","hasNAs","varmin","varmax","varpossvals")
    iframe <- iframe %>% bind_rows(k)
    
  }
  cov_meta[[q]] <- iframe
}

cov_meta_format <- cov_meta
covnotes <- read.csv(file="cov_pcr_metanotes.csv",stringsAsFactors=F)
notescols <- colnames(covnotes) %>% subset(grepl("notes",.))
for (q in 1:length(cov_meta_format)) {
  cov_meta_format[[q]]$varpossvals <- cov_meta_format[[q]][,c("varmin","varmax","varpossvals")] %>% apply(1,function(x) {if (is.na(x["varpossvals"])) {paste0(x["varmin"]," to ",x["varmax"])} else {x["varpossvals"]}})
  cov_meta_format[[q]]$varmin <- NULL
  cov_meta_format[[q]]$varmax <- NULL
  cov_meta_format[[q]]$couldbenum <- NULL
  cov_meta_format[[q]]$varpossvals <- cov_meta_format[[q]]$varpossvals %>% gsub(";","<BR>",.)
  colnames(cov_meta_format[[q]]) <- c("Variable name","Variable class","Are there NAs in this field?","Possible values or range of values")
  qnotes <- cov_meta_format[[q]]$`Variable name` %>% lapply(function(x) {covnotes %>% filter(dfname==names(cov_pcr_sera)[q] & Variable.name==x) %>% select(all_of(notescols))})
  cov_meta_format[[q]]$Notes <- qnotes %>% lapply(function(x) {x %>% unlist() %>% subset(.!="") %>% paste(collapse="<BR>")})
  
}
names(cov_meta_format) <- names(cov_pcr_sera)


```
report
```{r html}
maketable1 <- function (x) {
  htmltable <- "<table border=1>\n"
  htmltable <- htmltable %>% paste0("<tr align=center>")
  for (i in 1:ncol(x)) {
    htmltable <- htmltable %>% paste0("<td><B>",colnames(x)[i],"</B></td>")
  }
  htmltable <- htmltable %>% paste0("</tr>\n")
  for (j in 1:nrow(x)) {
    htmltable <- htmltable %>% paste0("<tr align=center>")
    for (k in 1:ncol(x)) {
      htmltable <- htmltable %>% paste0("<td>",x[j,k],"</td>")
    }
    htmltable <- htmltable %>% paste0("</tr>\n")
  }
  htmltable <- htmltable %>% paste0("</table><BR>\n")
  return(htmltable)
}

htmlreport <- "<HTML>\n"
#jquery for show hide elements
htmlreport <- htmlreport %>% paste0("<head><script src='https://code.jquery.com/jquery-3.5.1.min.js'></script>\n")
htmlreport <- htmlreport %>% paste0("<script>\n")
htmlreport <- htmlreport %>% paste0("$(document).ready(function() {\n")
htmlreport <- htmlreport %>% paste0("$(\"select\").change(function() {\n")
htmlreport <- htmlreport %>% paste0("$(this).find(\"option:selected\").each(function(){\n")
htmlreport <- htmlreport %>% paste0("var optionValue = $(this).attr(\"value\");\n")
htmlreport <- htmlreport %>% paste0("if(optionValue){\n$(\".block\").not(\".\" + optionValue).hide();\n")
htmlreport <- htmlreport %>% paste0("$(\".\" + optionValue).show();")
htmlreport <- htmlreport %>% paste0("} else {\n")
htmlreport <- htmlreport %>% paste0("$(\".block\").hide();\n}\n});\n}).change();\n});\n")
htmlreport <- htmlreport %>% paste0("</script></head>\n")

htmlreport <- htmlreport %>% paste0("<BODY>\n")
htmlreport <- htmlreport %>% paste0("<div>\n")

#head section
htmlreport <- htmlreport %>% paste0("<B>",sourcefile,"</B><BR>\n")
htmlreport <- htmlreport %>% paste0("<B>Source code:</B> <A HREF=\"https://gitlab.umiacs.umd.edu/catch/sars-shedding-manuscript/-/blob/master/analytical_cleaned_datasets/cov_pcr_meta.Rmd\" target='_blank'>cov_pcr_meta.Rmd</A></B><BR>\n")

htmlreport <- htmlreport %>% paste0("<B>Time of report: ",Sys.time() %>% as.POSIXct(tz="America/New_York"),"</B><P>\n")

htmlreport <- htmlreport %>% paste0(sourcefile," is a list of data frames: ",names(cov_meta_format) %>% paste(collapse=", "),".<P>\n")

# dropdown
htmlreport <- htmlreport %>% paste0("<select>\n")
htmlreport <- htmlreport %>% paste0("<option><B>Choose data frame:</B></option>\n")
for (i in 1:length(cov_meta_format)) {
  htmlreport <- htmlreport %>% paste0("<option value='",names(cov_meta_format)[i],"'>",names(cov_meta_format)[i],"</option>\n")
}
htmlreport <- htmlreport %>% paste0("</select><P>\n")
htmlreport <- htmlreport %>% paste0("</div>\n")
htmlreport <- htmlreport %>% paste0("<P><HR><P>\n")

for (q in 1:length(cov_meta_format)) {
  htmlreport <- htmlreport %>% paste0("<div class='",names(cov_meta_format)[q]," block'>\n")
  htmlreport <- htmlreport %>% paste0("Data frame: ",names(cov_meta_format)[q],"<BR>\n")
  htmlreport <- htmlreport %>% paste0(maketable1(cov_meta_format[[q]]))
  #htmlreport <- htmlreport %>% paste0("<HR><P>\n")
  htmlreport <- htmlreport %>% paste0("</div>\n")
}


htmlreport <- htmlreport %>% paste0("</BODY>\n</HTML>")
write(htmlreport,"cov_pcr_meta_report.html")
```